# Site setings
name: 'Jose Elera blogs here'
description: 'This is where me, Jose Elera, blogs about programming'
meta_description: 'Jose Elera blogs here about programming and open source and other topics'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  # image: 'authorimage.jpg'
  greetings: "Hi there! My name is Jose Elera. I'm a Full Stack Software Developer based in Chicago, IL. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://jelera.github.io/
# disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: jelera@gmail.com
# contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
# thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'jelera'
github: 'jelera'
linkedin: 'jose-elera'
stack-overflow: '428786/jose-elera'
# quora: 'username'
# codepen: 'username'
# facebook: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
# producthunt: '@username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other

markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
